Added responsive contact form with custom styling
devdaim6/department-of-it pull request #15
Opened 2024-07-20 17:45 UTC by Naveed-SNR

2024-07-20 17:47 UTC, devdaim6 commented
@Naveed-SNR cxe goy preview fail 



gode.karu su theek

2024-07-20 17:50 UTC, Naveed-SNR commented
> @Naveed-SNR cxe goy preview fail
> 
> gode.karu su theek

jo issues ma log h whi problem h na sirf

2024-07-20 17:58 UTC, Naveed-SNR commented
@devdaim6 check

2024-07-20 18:00 UTC, devdaim6 commented
![Screenshot_2024-07-20-23-29-35-80.jpg](https://github.com/user-attachments/assets/4a18fadf-6dae-4254-aad1-aa4a6e83e104)

image not required and button wech no border

2024-07-20 18:00 UTC, Naveed-SNR commented
> ![Screenshot_2024-07-20-23-29-35-80.jpg](https://private-user-images.githubusercontent.com/123406647/350710849-4a18fadf-6dae-4254-aad1-aa4a6e83e104.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0OTg3MTcsIm5iZiI6MTcyMTQ5ODQxNywicGF0aCI6Ii8xMjM0MDY2NDcvMzUwNzEwODQ5LTRhMThmYWRmLTZkYWUtNDI1NC1hYWQxLWFhNGE2ZTgzZTEwNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQxODAwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDczZjZiNmVhOTI5MDFmYjc3MWFiYjNlODg2ZTM3N2ZlN2RmYjQ4N2U1MjVmYzcyMTljNjEyOTE4MWY5MzcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.62nvl8F-h61uQYSWS5CTaVKxSGWAboO2Xs5r25oC39g)
> 
> image not required and button wech no border

yi chu lakut msle next commit ma thk karu ga

2024-07-20 18:01 UTC, Naveed-SNR commented
> > ![Screenshot_2024-07-20-23-29-35-80.jpg](https://private-user-images.githubusercontent.com/123406647/350710849-4a18fadf-6dae-4254-aad1-aa4a6e83e104.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0OTg3MTcsIm5iZiI6MTcyMTQ5ODQxNywicGF0aCI6Ii8xMjM0MDY2NDcvMzUwNzEwODQ5LTRhMThmYWRmLTZkYWUtNDI1NC1hYWQxLWFhNGE2ZTgzZTEwNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQxODAwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDczZjZiNmVhOTI5MDFmYjc3MWFiYjNlODg2ZTM3N2ZlN2RmYjQ4N2U1MjVmYzcyMTljNjEyOTE4MWY5MzcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.62nvl8F-h61uQYSWS5CTaVKxSGWAboO2Xs5r25oC39g)
> > image not required and button wech no border
> 
> yi chu lakut msle next commit ma thk karu ga

filhal kar  cxe merge

2024-07-20 18:01 UTC, devdaim6 commented
and i was thinking of adding a select button in contact too , for categorizing website bug realted contact , or information regarding clubs or something like this may b

2024-07-20 18:01 UTC, devdaim6 commented
Message me ? remove that🤣🤣

2024-07-20 18:02 UTC, Naveed-SNR commented
> and i was thinking of adding a select button in contact too , for categorizing website bug realted contact , or information regarding clubs or something like this may b

Ath ha chu teli UI ti shearun. Thav wo message ma hii user likhe ga

2024-07-20 18:02 UTC, devdaim6 commented
@Naveed-SNR

2024-07-20 18:03 UTC, devdaim6 commented
![Screenshot_2024-07-20-23-32-20-56.jpg](https://github.com/user-attachments/assets/7dffb870-0514-4721-aef2-17d8e3b1643f)

box ko nechay kaha amrica beja hai ? su haav ending if box beyi yus contact info chuna su lagav box nebre kani bone kani ....form aur footer ke beech mai

2024-07-20 18:05 UTC, Naveed-SNR commented
> ![Screenshot_2024-07-20-23-32-20-56.jpg](https://private-user-images.githubusercontent.com/123406647/350710973-7dffb870-0514-4721-aef2-17d8e3b1643f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0OTg4ODksIm5iZiI6MTcyMTQ5ODU4OSwicGF0aCI6Ii8xMjM0MDY2NDcvMzUwNzEwOTczLTdkZmZiODcwLTA1MTQtNDcyMS1hZWYyLTE3ZDhlM2IxNjQzZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQxODAzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjVkNjMwYTI1NmIzMjEwNmQzNWYzMTA4MmM2NjM4N2I2YjIzNTczZDQ5MDAzZDEyYmEyYzY1OTU5MjJkN2QzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kbSXgafUcPxr57TitKUBbLu77pnE4_GJ6N6D8kbH1Kg)
> 
> box ko nechay kaha amrica beja hai ? su haav ending if box beyi yus contact info chuna su lagav box nebre kani bone kani ....form aur footer ke beech mai

Ye badi screens p ajeeb hota h agr bahar nikale g box k

Ye acha h aise hii

2024-07-20 18:05 UTC, devdaim6 commented
on submit toast sonner i told you to use and clear form fields to ""

2024-07-20 18:06 UTC, Naveed-SNR commented
> on submit toast sonner i told you to use and clear form fields to ""

Sorui kati kar aki doh pga wechav waen su

2024-07-21 04:43 UTC, devdaim6 commented on app/components/ContactForm.jsx
> +      const formData = new FormData();
no need to make formData , simply pass the states which we have like this :
```js
body:JSON.stringify({
name,
email,
message,
image:image?image:""
})
```

2024-07-21 04:43 UTC, devdaim6 commented on app/components/ContactForm.jsx
> +    else if (!['image/jpeg', 'image/png'].includes(image.type)) newErrors.image = 'Only .jpg and .png files are allowed';
Image field is not requried remove the validation for that

2024-07-21 04:44 UTC, devdaim6 commented on app/components/ContactForm.jsx
> +                <div className="mb-4">
No border for submit button

2024-07-21 04:45 UTC, devdaim6 requested changes
Highlighted issues

2024-07-21 04:47 UTC, devdaim6 commented
![image](https://github.com/user-attachments/assets/3412f7d2-2aac-4d5f-b0d1-839a7c9dfb0d)


@TAWSEEFSHAMIM @Naveed-SNR why all the stuff on  a single page ? it should work either conditionally or just new route for the next step but for new routes you have to keeep track of previous state as well

2024-07-21 04:50 UTC, Naveed-SNR commented
> ![image](https://github.com/user-attachments/assets/3412f7d2-2aac-4d5f-b0d1-839a7c9dfb0d)
> 
> 
> @TAWSEEFSHAMIM @Naveed-SNR why all the stuff on  a single page ? it should work either conditionally or just new route for the next step but for new routes you have to keeep track of previous state as well

@TAWSEEFSHAMIM was only in charge of designing the sections. Arranging these is my part of the job and I'll start working on it today.

2024-07-21 04:54 UTC, Naveed-SNR commented
@devdaim6 merge this PR, anything that's not working will be fixed later.

2024-07-21 04:56 UTC, Naveed-SNR reviewed
Issues with the register page section will be fixed later.

2024-07-21 05:03 UTC, devdaim6 commented
> Issues with the register page section will be fixed later.

fix that then will merge no big deal......no fun of merging many PRs , just complete each step and merge.......and if you have to implement other  features better would be create a branch for that push that , and will merge that let it be until its complete , coz preview we have how and what it looks like https://department-of-it-git-dev-devdaims-projects.vercel.app/

2024-07-21 05:04 UTC, devdaim6 commented
just have contact and registration page here from now until we merge this until create new seperate branches for each feature , will be easy to manage / merge and probably no conflicts to resolve

2024-07-21 05:23 UTC, Naveed-SNR commented
> > Issues with the register page section will be fixed later.
> 
> fix that then will merge no big deal......no fun of merging many PRs , just complete each step and merge.......and if you have to implement other  features better would be create a branch for that push that , and will merge that let it be until its complete , coz preview we have how and what it looks like https://department-of-it-git-dev-devdaims-projects.vercel.app/

You should merge. Other contributors also have to pull and they may face issues like large no. of conflicts if there are too many commits in a single PR.

2024-07-21 05:29 UTC, devdaim6 commented
> > > Issues with the register page section will be fixed later.
> > 
> > 
> > fix that then will merge no big deal......no fun of merging many PRs , just complete each step and merge.......and if you have to implement other  features better would be create a branch for that push that , and will merge that let it be until its complete , coz preview we have how and what it looks like https://department-of-it-git-dev-devdaims-projects.vercel.app/
> 
> You should merge. Other contributors also have to pull and they may face issues like large no. of conflicts if there are too many commits in a single PR.

BARADAR THATS WHAT I SAID THEY WILL PULL FROM DEV BRANCH , AND FROM NOW ON CREATE SEPERATE BRANCH FOR EACH THING like events page will have seperate branch clubs etc, just complete this and then will merge it , it wont cause issue dont worry

2024-07-21 05:37 UTC, Naveed-SNR commented
> > > > Issues with the register page section will be fixed later.
> > > 
> > > 
> > > fix that then will merge no big deal......no fun of merging many PRs , just complete each step and merge.......and if you have to implement other  features better would be create a branch for that push that , and will merge that let it be until its complete , coz preview we have how and what it looks like https://department-of-it-git-dev-devdaims-projects.vercel.app/
> > 
> > 
> > You should merge. Other contributors also have to pull and they may face issues like large no. of conflicts if there are too many commits in a single PR.
> 
> BARADAR THATS WHAT I SAID THEY WILL PULL FROM DEV BRANCH , AND FROM NOW ON CREATE SEPERATE BRANCH FOR EACH THING like events page will have seperate branch clubs etc, just complete this and then will merge it , it wont cause issue dont worry

We're mostly working on one feature at a time, so the dev branch is enough, no need to create a separate branch for every thing. And convey to others that they have to pull from dev branch, if that's what we're doing.

2024-07-21 05:40 UTC, devdaim6 commented
> > > > > Issues with the register page section will be fixed later.
> > > > 
> > > > 
> > > > fix that then will merge no big deal......no fun of merging many PRs , just complete each step and merge.......and if you have to implement other  features better would be create a branch for that push that , and will merge that let it be until its complete , coz preview we have how and what it looks like https://department-of-it-git-dev-devdaims-projects.vercel.app/
> > > 
> > > 
> > > You should merge. Other contributors also have to pull and they may face issues like large no. of conflicts if there are too many commits in a single PR.
> > 
> > 
> > BARADAR THATS WHAT I SAID THEY WILL PULL FROM DEV BRANCH , AND FROM NOW ON CREATE SEPERATE BRANCH FOR EACH THING like events page will have seperate branch clubs etc, just complete this and then will merge it , it wont cause issue dont worry
> 
> We're mostly working on one feature at a time, so the dev branch is enough, no need to create a separate branch for every thing. And convey to others that they have to pull from dev branch, if that's what we're doing.


converying doesnt make any diff sometimes we just push new commit and i cant review every single detail in every commit thats why if everyone create seperate branch for seperate stuff that wont cause any issues otherwise i have no issues on working only on dev , but its getting complicated day by day because codebase is filling up , cant review every minute step of every commit change

2024-07-21 05:46 UTC, Naveed-SNR commented
> > > > > > Issues with the register page section will be fixed later.
> > > > > 
> > > > > 
> > > > > fix that then will merge no big deal......no fun of merging many PRs , just complete each step and merge.......and if you have to implement other  features better would be create a branch for that push that , and will merge that let it be until its complete , coz preview we have how and what it looks like https://department-of-it-git-dev-devdaims-projects.vercel.app/
> > > > 
> > > > 
> > > > You should merge. Other contributors also have to pull and they may face issues like large no. of conflicts if there are too many commits in a single PR.
> > > 
> > > 
> > > BARADAR THATS WHAT I SAID THEY WILL PULL FROM DEV BRANCH , AND FROM NOW ON CREATE SEPERATE BRANCH FOR EACH THING like events page will have seperate branch clubs etc, just complete this and then will merge it , it wont cause issue dont worry
> > 
> > 
> > We're mostly working on one feature at a time, so the dev branch is enough, no need to create a separate branch for every thing. And convey to others that they have to pull from dev branch, if that's what we're doing.
> 
> converying doesnt make any diff sometimes we just push new commit and i cant review every single detail in every commit thats why if everyone create seperate branch for seperate stuff that wont cause any issues otherwise i have no issues on working only on dev , but its getting complicated day by day because codebase is filling up , cant review every minute step of every commit change

You still have to inform everyone that they've to pull from dev branch and not main (because most of them don't know dev is ahead of main). As far as different branches go, only I am working on something currently so I'll push to dev. If I or someone else starts working on something else, we'll create a different branch.

2024-07-21 05:50 UTC, devdaim6 commented
> > > > > > > Issues with the register page section will be fixed later.
> > > > > > 
> > > > > > 
> > > > > > fix that then will merge no big deal......no fun of merging many PRs , just complete each step and merge.......and if you have to implement other  features better would be create a branch for that push that , and will merge that let it be until its complete , coz preview we have how and what it looks like https://department-of-it-git-dev-devdaims-projects.vercel.app/
> > > > > 
> > > > > 
> > > > > You should merge. Other contributors also have to pull and they may face issues like large no. of conflicts if there are too many commits in a single PR.
> > > > 
> > > > 
> > > > BARADAR THATS WHAT I SAID THEY WILL PULL FROM DEV BRANCH , AND FROM NOW ON CREATE SEPERATE BRANCH FOR EACH THING like events page will have seperate branch clubs etc, just complete this and then will merge it , it wont cause issue dont worry
> > > 
> > > 
> > > We're mostly working on one feature at a time, so the dev branch is enough, no need to create a separate branch for every thing. And convey to others that they have to pull from dev branch, if that's what we're doing.
> > 
> > 
> > converying doesnt make any diff sometimes we just push new commit and i cant review every single detail in every commit thats why if everyone create seperate branch for seperate stuff that wont cause any issues otherwise i have no issues on working only on dev , but its getting complicated day by day because codebase is filling up , cant review every minute step of every commit change
> 
> You still have to inform everyone that they've to pull from dev branch and not main (because most of them don't know dev is ahead of main). As far as different branches go, only I am working on something currently so I'll push to dev. If I or someone else starts working on something else, we'll create a different branch.

you have tawseef working as well , he did his part on registration part give , now he will create a basic login form : @TAWSEEFSHAMIM  create a branch login , route /auth/login  -> fields = username or email then password bas thats all and have a forgotpassword? link  below that login button bas

2024-07-21 05:51 UTC, devdaim6 commented
> > > > > > > Issues with the register page section will be fixed later.
> > > > > > 
> > > > > > 
> > > > > > fix that then will merge no big deal......no fun of merging many PRs , just complete each step and merge.......and if you have to implement other  features better would be create a branch for that push that , and will merge that let it be until its complete , coz preview we have how and what it looks like https://department-of-it-git-dev-devdaims-projects.vercel.app/
> > > > > 
> > > > > 
> > > > > You should merge. Other contributors also have to pull and they may face issues like large no. of conflicts if there are too many commits in a single PR.
> > > > 
> > > > 
> > > > BARADAR THATS WHAT I SAID THEY WILL PULL FROM DEV BRANCH , AND FROM NOW ON CREATE SEPERATE BRANCH FOR EACH THING like events page will have seperate branch clubs etc, just complete this and then will merge it , it wont cause issue dont worry
> > > 
> > > 
> > > We're mostly working on one feature at a time, so the dev branch is enough, no need to create a separate branch for every thing. And convey to others that they have to pull from dev branch, if that's what we're doing.
> > 
> > 
> > converying doesnt make any diff sometimes we just push new commit and i cant review every single detail in every commit thats why if everyone create seperate branch for seperate stuff that wont cause any issues otherwise i have no issues on working only on dev , but its getting complicated day by day because codebase is filling up , cant review every minute step of every commit change
> 
> You still have to inform everyone that they've to pull from dev branch and not main (because most of them don't know dev is ahead of main). As far as different branches go, only I am working on something currently so I'll push to dev. If I or someone else starts working on something else, we'll create a different branch.

@Naveed-SNR cxe maklaav contact poore fix kaerith beyi kar registration khatam baki wechov patte

2024-07-21 11:21 UTC, devdaim6 commented
![image](https://github.com/user-attachments/assets/a6fae455-215a-4d01-aef9-b7b77f4e3ce5)


NAVEED first thing , dont craete FormData , sending state sedhay as json string in body and second thing when form is submitted without data , errors are displayed but when user changes name email and message state respective errors should get removed on state change

2024-07-21 11:21 UTC, devdaim6 commented on app/components/ContactForm.jsx
> +      const formData = new FormData();
> no need to make formData , simply pass the states which we have like this :
> 
> ```js
> body:JSON.stringify({
> name,
> email,
> message,
> image:image?image:""
> })
> ```

YE WECH

2024-07-21 11:50 UTC, devdaim6 commented
[17:19:00.917] Running build in Washington, D.C., USA (East) – iad1
[17:19:01.029] Cloning github.com/devdaim6/department-of-it (Branch: dev, Commit: 15f5744)
[17:19:01.350] Cloning completed: 320.99ms
[17:19:03.709] Restored build cache
[17:19:03.781] Running "vercel build"
[17:19:04.250] Vercel CLI 35.1.0
[17:19:04.600] Running "install" command: `npm install --legacy-peer-deps`...
[17:19:06.004] 
[17:19:06.004] up to date, audited 452 packages in 1s
[17:19:06.004] 
[17:19:06.004] 144 packages are looking for funding
[17:19:06.004]   run `npm fund` for details
[17:19:06.005] 
[17:19:06.005] found 0 vulnerabilities
[17:19:06.016] Detected Next.js version: 14.2.5
[17:19:06.019] Detected `package-lock.json` generated by npm 7+
[17:19:06.020] Running "npm run build"
[17:19:06.207] 
[17:19:06.207] > department-of-it@0.1.0 build
[17:19:06.207] > next build
[17:19:06.207] 
[17:19:06.882]   ▲ Next.js 14.2.5
[17:19:06.883] 
[17:19:06.960]    Creating an optimized production build ...
[17:19:20.448]  ✓ Compiled successfully
[17:19:20.449]    Linting and checking validity of types ...
[17:19:22.076] 
[17:19:22.076] Failed to compile.
[17:19:22.076] 
[17:19:22.076] ./app/register/clubs.jsx
[17:19:22.076] 71:15  Error: Missing "key" prop for element in iterator  react/jsx-key
[17:19:22.076] 
[17:19:22.077] info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
[17:19:22.097] Error: Command "npm run build" exited with 1
[17:19:23.352] 


@Naveed-SNR

2024-07-21 11:51 UTC, Naveed-SNR commented
> [17:19:00.917] Running build in Washington, D.C., USA (East) – iad1 [17:19:01.029] Cloning github.com/devdaim6/department-of-it (Branch: dev, Commit: [15f5744](https://github.com/devdaim6/department-of-it/commit/15f5744c00a9924c394c3c2dac22295d426f4585)) [17:19:01.350] Cloning completed: 320.99ms [17:19:03.709] Restored build cache [17:19:03.781] Running "vercel build" [17:19:04.250] Vercel CLI 35.1.0 [17:19:04.600] Running "install" command: `npm install --legacy-peer-deps`... [17:19:06.004] [17:19:06.004] up to date, audited 452 packages in 1s [17:19:06.004] [17:19:06.004] 144 packages are looking for funding [17:19:06.004] run `npm fund` for details [17:19:06.005] [17:19:06.005] found 0 vulnerabilities [17:19:06.016] Detected Next.js version: 14.2.5 [17:19:06.019] Detected `package-lock.json` generated by npm 7+ [17:19:06.020] Running "npm run build" [17:19:06.207] [17:19:06.207] > department-of-it@0.1.0 build [17:19:06.207] > next build [17:19:06.207] [17:19:06.882] ▲ Next.js 14.2.5 [17:19:06.883] [17:19:06.960] Creating an optimized production build ... [17:19:20.448] ✓ Compiled successfully [17:19:20.449] Linting and checking validity of types ... [17:19:22.076] [17:19:22.076] Failed to compile. [17:19:22.076] [17:19:22.076] ./app/register/clubs.jsx [17:19:22.076] 71:15 Error: Missing "key" prop for element in iterator react/jsx-key [17:19:22.076] [17:19:22.077] info - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules [17:19:22.097] Error: Command "npm run build" exited with 1 [17:19:23.352]
> 
> @Naveed-SNR



Wait yehi thk kr rha hu

2024-07-21 11:56 UTC, devdaim6 approved these changes

2024-07-21 11:56 UTC, merged

2024-07-21 11:57 UTC, devdaim6 commented
![image](https://github.com/user-attachments/assets/82a317fc-d4d3-4fe4-9d36-31b055f8bf84)


@Naveed-SNR chuyna cxaer aasan gomut : fullname is not updating ath chuyni onchange chalaney

2024-07-21 11:58 UTC, devdaim6 commented
ath chune typey gasan

2024-07-21 11:58 UTC, Naveed-SNR commented
> ath chune typey gasan
> 

Wni hy chalan os

2024-07-21 11:59 UTC, Naveed-SNR commented
> ath chune typey gasan
> 

Cxe kyazi 4 lati same msg kermicx

2024-07-21 12:00 UTC, devdaim6 commented
![image](https://github.com/user-attachments/assets/68030f94-a28f-4619-bc79-76187107c73b)


> > ath chune typey gasan
> 
> Cxe kyazi 4 lati same msg kermicx

2024-07-21 12:03 UTC, Naveed-SNR commented
> ![image](https://github.com/user-attachments/assets/68030f94-a28f-4619-bc79-76187107c73b)
> 
> 
> > > ath chune typey gasan
> > 
> > Cxe kyazi 4 lati same msg kermicx
> 
> 

GitHub pareshan isko sync issues h

2024-07-21 12:08 UTC, devdaim6 commented
wani kar ye issue theek te naev pr kar pat kaerzi kaem events ya clubs kaerzi start banavun mai chu tami hissab tath bakend banavun

2024-07-21 12:08 UTC, devdaim6 commented
cluubs rozan static su thavav hardcoded

2024-07-21 12:08 UTC, devdaim6 commented
@Naveed-SNR